### ISSUE TITLE
Just a questions

### ISSUE THREAD

**Issue by nestquik** [maelgrove/gemini-experimental#16]
What tool do u use to format code? If it's ReSharper could u provide settings file to repo?

**Comment by maelgrove** [comment]
Hi there. Sorry for the delay! I am indeed using ReSharper, but I don't have any special settings besides the defaults used in ReSharper Ultimate 2017.1.2.

If you're asking because you'd like to sync up our code style (yeah, I shouldn't have done full cleanups over the entire source, but I didn't expected others to use my fork at all), I don't think that there would be any point in it as I'm not planning to further work on gemini-experimental. I'm currently working on my own shell framework inspired by gemini which will target multiple platforms through .NET core (supporting WPF and Xamarin.Forms) as soon as Caliburn.Micro 4 reaches somewhat of an alpha state. :)
